from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Form5(object):
    def open_Captains(self):
        from captains import Ui_Form4
        self.window7 = QtWidgets.QMainWindow()
        self.ui = Ui_Form4()
        self.ui.setupUi(self.window7)
        self.window7.show()
    def open_New_Player(self):
        from inter_the_info import Ui_Form3
        self.window6 = QtWidgets.QMainWindow()
        self.ui = Ui_Form3()
        self.ui.setupUi(self.window6)
        self.window6.show()
    def open_Info(self):
        from info_about_player import Ui_Form2
        self.window5 = QtWidgets.QMainWindow()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.window5)
        self.window5.show()
    def setupUi(self, Form5):
        Form5.setObjectName("Form5")
        Form5.resize(776, 717)
        Form5.setMaximumSize(776, 717)
        Form5.setWindowIcon(QtGui.QIcon("gym-icon_30328.ico"))
        Form5.setStyleSheet("background-color: rgb(248, 147, 31);")
        f1 = Form5.menuBar().addMenu("Options")
        f1.setStyleSheet("background-color:  rgb(248, 132, 31);")
        e = QtWidgets.QAction(QIcon('football_player_sport_olympic_player_icon_123803.ico')," New Player ", Form5)
        e1 = QtWidgets.QAction(QIcon('new_add_user_info_16706.ico')," Info Player", Form5)
        e2 = QtWidgets.QAction(QIcon('medal_champion_award_winner_olympic_icon_207819.ico')," Captains   ", Form5)
       #e3 = QtWidgets.QAction(" Prices     ", Form5)

        def ff():
            print("new")

        e.triggered.connect(self.open_New_Player)
        e.triggered.connect(Form5.close)
        e1.triggered.connect(self.open_Info)
        e1.triggered.connect(Form5.close)
        e2.triggered.connect(self.open_Captains)
        e2.triggered.connect(Form5.close)
        #e3.triggered.connect(ff)
        f1.addAction(e)
        f1.addAction(e1)
        f1.addAction(e2)
        #f1.addAction(e3)
        self.tableWidget = QtWidgets.QTableWidget(Form5)
        self.tableWidget.setGeometry(QtCore.QRect(210, 180, 371, 241))
        self.tableWidget.setStyleSheet("background-color: rgb(238, 233, 233);\n"
                                       "color: rgb(0, 0, 0);\n"
                                       "gridline-color:  rgb(0, 0, 0);\n"
                                       "")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        self.label_29 = QtWidgets.QLabel(Form5)
        self.label_29.setGeometry(QtCore.QRect(240, 30, 310, 41))
        self.label_29.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
                                    "font: 24pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")

        self.retranslateUi(Form5)
        QtCore.QMetaObject.connectSlotsByName(Form5)

    def retranslateUi(self, Form5):
        _translate = QtCore.QCoreApplication.translate
        Form5.setWindowTitle(_translate("Form5", "Prices"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form5", "Silver1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form5", "Silver2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form5", "Gold1"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form5", "Gold2"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form5", "Diamond1"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form5", "Diamond2"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form5", "Premium"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form5", "Price"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form5", "Times"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form5", "Offer"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form5", "150"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form5", "8"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form5", "190"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form5", "12"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form5", "225"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form5", "16"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form5", "265"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form5", "30"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form5", "...."))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form5", "3month"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form5", "20%"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form5", "...."))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form5", "6month"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form5", "30%"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form5", "....."))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form5", "1year"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form5", "40%"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_29.setText(_translate("Form5", "Prices And Offers"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form5 = QtWidgets.QMainWindow()
    ui = Ui_Form5()
    ui.setupUi(Form5)
    Form5.show()
    sys.exit(app.exec_())
